


spring:
  application:
    name: timesheet-service


  data:
    mongodb:
      uri: mongodb+srv://newuser1:19960709@timesheet.psmbg.mongodb.net/timesheet?retryWrites=true&w=majority
      database: timesheet


server:
  port: 0
